# Generated by Django 3.0 on 2019-12-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='book title', max_length=200, null=True)),
                ('description', models.TextField(default='book description')),
            ],
        ),
    ]
