# Generated by Django 3.0 on 2019-12-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0004_auto_20191206_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this book. Generated by the system.', max_length=300),
        ),
    ]
