from django.db import models
from django.utils.text import slugify
# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length = 200, default='book title', null=True)
    description = models.TextField(default='book description')
    slug = models.CharField(max_length=300, blank=True, editable=False,
                            help_text="Unique URL path to access this book. Generated by the system.")
    
    def get_absolute_url(self):
        """ Returns a fully-qualified path for a page (/my-new-wiki-page). """
        path_components = {'slug': self.slug}
        return reverse('wiki-details-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a page is created. """
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Book, self).save(*args, **kwargs)

class Comment(models.Model):
    RATING_RANGE = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    )
    comment = models.TextField(default='book comment')
    rating = models.IntegerField(choices=RATING_RANGE, default=RATING_RANGE[0][0])
    book = models.ForeignKey(Book, on_delete = models.CASCADE)
    def __str__(self):
        return self.comment
        