# Generated by Django 3.0 on 2019-12-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='book comment')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Book')),
            ],
        ),
    ]
