# Generated by Django 2.2.6 on 2019-12-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0006_auto_20191207_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='book description'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this book. Generated by the system.', max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='book title', max_length=200, null=True),
        ),
    ]
