# Generated by Django 2.2.6 on 2019-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0007_auto_20191207_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='book author', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0000', help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='book image url', max_length=400, null=True),
        ),
    ]
